---
language: python
python: "2.7"

env:
    - ANSIBLE_VERSION=1.6
    - ANSIBLE_VERSION=1.7

install:
    # Install Ansible
    - pip install ansible==$ANSIBLE_VERSION

    # Add ansible.cfg to pick up roles path.
    - "printf '[defaults]\nroles_path = ../' > ansible.cfg"

script:
    # Check playbook's syntax
    - "ansible-playbook -i tests/inventory tests/test.yml --syntax-check"

    # Run playbook
    - "ansible-playbook -i tests/inventory tests/test.yml --connection=local --sudo -vvvv"

    # Run the playbook again, checking to make sure it's idempotent.
    - >
      ansible-playbook -i tests/inventory tests/test.yml --connection=local --sudo
      | grep -q 'changed=0.*failed=0'
      && (echo 'Idempotence test: pass' && exit 0)
      || (echo 'Idempotence test: fail' && exit 1)

notifications:
    email: false
