---
language: python
python: "2.7"

env:
    - ANSIBLE_VERSION=1.9.4

install:
    # Install Ansible
    - pip install ansible==$ANSIBLE_VERSION

    # Add ansible.cfg to pick up roles path.
    - "printf '[defaults]\nroles_path = ../' > ansible.cfg"

script:
    # Check playbook's syntax
    - "ansible-playbook -i tests/inventory tests/test.yml --syntax-check"

    # Run playbook
    - "ansible-playbook -i tests/inventory tests/test.yml --connection=local --sudo -vvvv"

notifications:
    email: false
