---
- name: Set Hostname with hostname command
  hostname: name="{{ hostname }}"

- name: Re-gather facts
  action: setup
  when: ansible_hostname != fqdn

# Idempotent way to build a /etc/hosts file with Ansible using your Ansible hosts inventory for a source.
# Will include all hosts the playbook is run on.
# Credits to rothgar: https://gist.github.com/rothgar/8793800
- name: Build hosts file (backups will be made)
  lineinfile: dest=/etc/hosts line='{{ hostvars[item].ansible_default_ipv4.address }} {{ hostvars[item].ansible_hostname }}  {{ item }}' state=present backup=yes
  when: hostvars[item].ansible_default_ipv4.address is defined
  with_items: groups['all']

- name: restart hostname
  service: name=hostname state=restarted
  async: 45
  poll: 0
